const PROJECT='the-chakna-point';
const products=[['Chicken Kasa',70],['Chicken Pakoda',70],['Chicken Liver',70],['Egg Omelette',50],['Egg Chop',40],['Mutton',80],['Sprite',20],['Thums Up',20],['Water Bottle',20],['Kurkure Legs',20],['Cigarette Packet',0]];
let cart={}; const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.hidden=true);$(id).hidden=false}
function renderMenu(){$('menu').innerHTML=products.map((p,i)=>`<div class="item"><h3>${p[0]}</h3><div class="price">${p[1]?'₹'+p[1]:'Price on request'}</div>${p[1]?`<button class="add" onclick="add(${i})">Add</button>`:''}</div>`).join('')}
function add(i){cart[i]=(cart[i]||0)+1;renderCartBar()}
function change(i,d){cart[i]=(cart[i]||0)+d;if(cart[i]<=0)delete cart[i];renderCart();renderCartBar()}
function totals(){const sub=Object.entries(cart).reduce((s,[i,q])=>s+products[i][1]*q,0);const delivery=sub?30:0;return{sub,delivery,total:sub+delivery}}
function renderCartBar(){const n=Object.values(cart).reduce((a,b)=>a+b,0),t=totals();$('cartCount').textContent=n;$('cartTotal').textContent=t.total}
function renderCart(){const rows=Object.entries(cart).map(([i,q])=>`<div class="cart-row"><span>${products[i][0]}<br>₹${products[i][1]} × ${q}</span><span class="qty"><button onclick="change(${i},-1)">−</button><b>${q}</b><button onclick="change(${i},1)">+</button></span></div>`).join('');$('cartItems').innerHTML=rows||'<p>Your cart is empty.</p>';const t=totals();$('subtotal').textContent='₹'+t.sub;$('delivery').textContent='₹'+t.delivery;$('grandTotal').textContent='₹'+t.total}
function fsValue(v){if(typeof v==='number')return {integerValue:String(v)};return {stringValue:String(v)}}
async function saveOrder(order){const fields={};for(const [k,v] of Object.entries(order)){if(k==='items'){fields[k]={arrayValue:{values:v.map(x=>({mapValue:{fields:{name:fsValue(x.name),price:fsValue(x.price),quantity:fsValue(x.quantity)}}}))}}}else fields[k]=fsValue(v)}const body={fields};const url=`https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents/orders`;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('Order server error: '+await r.text());return r.json()}
$('openCart').onclick=()=>{renderCart();show('cart')};$('backHome').onclick=()=>show('home');$('continue').onclick=()=>{cart={};renderCartBar();show('home')};$('locationBtn').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>$('address').value=`Current location: ${p.coords.latitude}, ${p.coords.longitude}`,()=>alert('Location permission nahi mila.')):alert('Location supported nahi hai.');
$('placeOrder').onclick=async()=>{try{const t=totals();if(!t.sub)throw Error('Cart empty.');const name=$('name').value.trim(),address=$('address').value.trim();if(!name||!address)throw Error('Name aur address bhariye.');$('orderMsg').textContent='Placing order...';const items=Object.entries(cart).map(([i,q])=>({name:products[i][0],price:products[i][1],quantity:q}));await saveOrder({name,address,items,subtotal:t.sub,deliveryCharge:t.delivery,total:t.total,payment:$('payment').value,paymentStatus:'Pending',status:'New',createdAt:new Date().toISOString()});$('orderMsg').textContent='';show('success')}catch(e){console.error(e);$('orderMsg').textContent=e.message}}
renderMenu();renderCartBar();
