package com.thechaknapoint.customer;

import android.os.Bundle;import android.text.InputFilter;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;
import com.google.firebase.FirebaseException;import com.google.firebase.auth.*;import com.google.firebase.firestore.*;import java.util.*;import java.util.concurrent.TimeUnit;

public class MainActivity extends AppCompatActivity {
  EditText phone,otp,name,address; Button send,verify,viewCart,place,back,logout; TextView msg,summary,totals,orderMsg; LinearLayout login,home,cart,menu,cartItems; Spinner payment; FirebaseAuth auth; FirebaseFirestore db; PhoneAuthProvider.ForceResendingToken resendToken; String verificationId; int[] qty=new int[9];
  String[] products={"Chicken Pakoda","Chicken Kasa","Chicken Liver","Chicken Curry","Egg Omelet","Egg Chap","Papad","Water Bottle","Cold Drink"}; int[] prices={70,70,60,70,50,40,20,20,20};
  @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);auth=FirebaseAuth.getInstance();db=FirebaseFirestore.getInstance(); bind(); if(auth.getCurrentUser()!=null) showHome(); else showLogin();}
  void bind(){phone=findViewById(R.id.phone);otp=findViewById(R.id.otp);send=findViewById(R.id.sendOtp);verify=findViewById(R.id.verifyOtp);msg=findViewById(R.id.loginMsg);login=findViewById(R.id.loginPanel);home=findViewById(R.id.homePanel);cart=findViewById(R.id.cartPanel);menu=findViewById(R.id.menu);cartItems=findViewById(R.id.cartItems);summary=findViewById(R.id.cartSummary);totals=findViewById(R.id.totals);name=findViewById(R.id.name);address=findViewById(R.id.address);payment=findViewById(R.id.payment);place=findViewById(R.id.placeOrder);orderMsg=findViewById(R.id.orderMsg);viewCart=findViewById(R.id.viewCart);back=findViewById(R.id.backHome);logout=findViewById(R.id.logout);payment.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Cash on Delivery","UPI"}));send.setOnClickListener(v->sendOtp());verify.setOnClickListener(v->verifyOtp());viewCart.setOnClickListener(v->{renderCart();showCart();});back.setOnClickListener(v->showHome());logout.setOnClickListener(v->{auth.signOut();Arrays.fill(qty,0);showLogin();});place.setOnClickListener(v->placeOrder());}
  boolean valid(String s){return s.matches("[6-9][0-9]{9}");}
  void sendOtp(){String p=phone.getText().toString().trim();if(!valid(p)){msg.setText("Sahi 10-digit mobile number bhariye.");return;}msg.setText("OTP bheja ja raha hai..."); PhoneAuthOptions options=PhoneAuthOptions.newBuilder(auth).setPhoneNumber("+91"+p).setTimeout(60L,TimeUnit.SECONDS).setActivity(this).setCallbacks(new PhoneAuthProvider.OnVerificationStateChangedCallbacks(){public void onVerificationCompleted(PhoneAuthCredential c){auth.signInWithCredential(c).addOnCompleteListener(t->{if(t.isSuccessful())showHome();});} public void onVerificationFailed(FirebaseException e){msg.setText(e.getMessage());send.setEnabled(true);} public void onCodeSent(String id,PhoneAuthProvider.ForceResendingToken token){verificationId=id;resendToken=token;otp.setVisibility(View.VISIBLE);verify.setVisibility(View.VISIBLE);send.setEnabled(false);msg.setText("OTP SMS mein bheja gaya hai.");}}).build();PhoneAuthProvider.verifyPhoneNumber(options);}
  void verifyOtp(){String code=otp.getText().toString().trim();if(verificationId==null||!code.matches("[0-9]{6}")){msg.setText("6-digit OTP dijiye.");return;}msg.setText("Login ho raha hai...");PhoneAuthCredential c=PhoneAuthProvider.getCredential(verificationId,code);auth.signInWithCredential(c).addOnCompleteListener(t->{if(t.isSuccessful())showHome();else msg.setText(t.getException()!=null?t.getException().getMessage():"OTP galat hai.");});}
  void showLogin(){login.setVisibility(View.VISIBLE);home.setVisibility(View.GONE);cart.setVisibility(View.GONE);otp.setVisibility(View.GONE);verify.setVisibility(View.GONE);send.setEnabled(true);msg.setText("");}
  void showHome(){login.setVisibility(View.GONE);home.setVisibility(View.VISIBLE);cart.setVisibility(View.GONE);renderMenu();renderSummary();}
  void showCart(){login.setVisibility(View.GONE);home.setVisibility(View.GONE);cart.setVisibility(View.VISIBLE);}
  void renderMenu(){menu.removeAllViews();for(int i=0;i<9;i++){final int x=i;LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setPadding(0,12,0,12);TextView t=new TextView(this);t.setText(products[i]+"\n₹"+prices[i]);t.setTextSize(17);row.addView(t,new LinearLayout.LayoutParams(0,-2,1));Button a=new Button(this);a.setText("Add");a.setOnClickListener(v->{qty[x]++;renderSummary();});row.addView(a);menu.addView(row);}}
  int sub(){int s=0;for(int i=0;i<9;i++)s+=qty[i]*prices[i];return s;} void renderSummary(){int n=0;for(int q:qty)n+=q;int s=sub();summary.setText("Cart: "+n+" items  •  ₹"+(s==0?0:s+30));}
  void renderCart(){cartItems.removeAllViews();int s=sub();for(int i=0;i<9;i++)if(qty[i]>0){final int x=i;TextView t=new TextView(this);t.setText(products[i]+"  ₹"+prices[i]+" × "+qty[i]);t.setTextSize(17);t.setPadding(0,10,0,10);cartItems.addView(t);}totals.setText("Subtotal: ₹"+s+"\nDelivery: ₹"+(s>0?30:0)+"\nTotal: ₹"+(s+(s>0?30:0)));}
  void placeOrder(){FirebaseUser u=auth.getCurrentUser();int s=sub();if(u==null){orderMsg.setText("Pehle OTP se login karein.");return;}if(s==0){orderMsg.setText("Cart empty.");return;}String n=name.getText().toString().trim(),a=address.getText().toString().trim();if(n.isEmpty()||a.isEmpty()){orderMsg.setText("Name aur address bhariye.");return;}List<Map<String,Object>> items=new ArrayList<>();for(int i=0;i<9;i++)if(qty[i]>0){Map<String,Object> m=new HashMap<>();m.put("name",products[i]);m.put("price",prices[i]);m.put("quantity",qty[i]);items.add(m);}Map<String,Object> o=new HashMap<>();o.put("customerUid",u.getUid());o.put("name",n);o.put("phone",u.getPhoneNumber());o.put("address",a);o.put("items",items);o.put("subtotal",s);o.put("deliveryCharge",30);o.put("total",s+30);o.put("payment",payment.getSelectedItem().toString().startsWith("UPI")?"UPI":"COD");o.put("paymentStatus","Pending");o.put("status","New");o.put("createdAt",FieldValue.serverTimestamp());orderMsg.setText("Order place ho raha hai...");db.collection("orders").add(o).addOnSuccessListener(x->{Arrays.fill(qty,0);renderSummary();orderMsg.setText("Order placed! The Chakna Point ko mil gaya.");}).addOnFailureListener(e->orderMsg.setText(e.getMessage()));}
}
